version = 3
final_space = true
enable_cursor_positioning = true
shell_integration = true
console_title_template = '{{ .Shell }} : {{ .PWD }}'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ .Full }}{{ end }}'
    foreground = 'lightWhite'
	background = 'blue'
    type = 'python'
    style = 'diamond'
	leading_diamond = ""
	trailing_diamond = " "

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    template = '# '
    foreground = 'lightBlue'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' % '
    foreground = 'red'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '<cyan>{{ .UserName }}</> <lightYellow>@</> <green>{{ .HostName }}</> '
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = ' C:{{ if gt .Code 0 }}{{ .Code }}{{ end }} '
	foreground = 'red'
	type = 'status'
	style = 'plain'

  [[blocks.segments]]
	template = ' [{{ .CurrentDate | date .Format }}] '
	foreground = 'lightBlue'
	type = 'time'
	style = 'plain'

  [[blocks.segments]]
    template = '{{ if gt .SHLVL 1 }}depth: {{ .SHLVL }}{{ end }} '
	foreground = 'red'
	type = 'text'
	style = 'plain'

  [[blocks.segments]]
    template = '<darkGray>-</> 󰔛 {{ .FormattedMs }}'
	type = 'executiontime'
	style = 'plain'
	foreground = 'lightMagenta'

	[blocks.segments.properties]
	threshold = 500
	style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '<lightBlue>in </>{{ .Path }} '
    foreground = 'lightYellow'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      fetch_status = true
	  fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '$'
    foreground = 'lightRed'
    type = 'text'
    style = 'plain'

[transient_prompt]
  foreground = 'lightRed'
  background = 'transparent'
  template = '$ '
