#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################
export NB_MARKDOWN_TOOL="mdcat"
export NB_IMAGE_TOOL="viu"
export NB_DIRECTORY_TOOL="lsd"

export NB_AUTO_SYNC="${NB_AUTO_SYNC:-0}" # Set by `nb` • 西元2024年10月13日 (週日) 16時47分51秒 CST
