[flavor]
dark = "dracula"
#dark = "tokyo-night"
#dark = "kanagawa"
#dark = "monokai-vibrant"
#dark = "gruvbox-dark"
#dark = "catppuccin-macchiato"
#dark = "everforest-medium"

[mode]

normal_main = { fg = "#282a36", bg = "#bd93f9", bold = true }
normal_alt	= { fg = "#f8f8f2", bg = "#44475a" }

select_main = { fg = "#282a36", bg = "yellow", bold = true }
select_alt	= { fg = "#f8f8f2", bg = "#44475a" }

unset_main	= { fg = "#282a36", bg = "red", bold = true }
unset_alt	= { fg = "#f8f8f2", bg = "#44475a" }

[mgr]

count_copied   = { fg = "#282a36", bg = "green" }
count_cut      = { fg = "#282a36", bg = "red" }
count_selected = { fg = "#282a36", bg = "yellow" }

[status]

sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
