"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [ 2, 3, 3 ]

[preview]
max_width = 800
max_height = 1100

[opener]
edit = [
	{ run = 'vim "$@"',  desc = "$EDITOR", block = true,  for = "unix" },
	{ run = 'nvim "$@"', desc = "neovim",  block = true,  for = "unix" },
	{ run = 'code "$@"', desc = "code",    orphan = true, for = "unix" },
]

extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
	{ run = 'ouch d "$@" -y', desc = "Extract here with ouch", for = "unix" },
]

markdown = [
	{ run = 'glow -p "$@"', block = true, desc = "view (glow)", for = "linux" },
]

show = [
	#{ run = 'imv "$@"', orphan = true, for = "unix" },
	{ run = 'qimgv "$@"', orphan = true, for = "unix" },
]

open = [
	{ run = 'xdg-open "$1"', desc = "Open", for = "linux" },
	#{ run = '''ya emit shell --block -- 'mimeopen -a "$1"'''', desc = "Mimeopen", block = true, for = "linux" },
	{ run = 'mimeopen -a "$1";echo "Press Enter to continue...";read _', desc = "Mimeopen", block = true, for = "linux" },
]

[open]
prepend_rules = [
	{ name = "*.md", use = [ "edit", "markdown", "open", "reveal" ] },
	{ name = "*.html", use = [ "edit", "open", "reveal" ] },
	{ mime = "image/*", use = [ "show", "open", "reveal" ] },
]

[plugin]
prepend_previewers = [
	{ mime = "application/*zip",          run = "ouch" },
	{ mime = "application/tar",           run = "ouch" },
	{ mime = "application/bzip2",         run = "ouch" },
	{ mime = "application/7z-compressed", run = "ouch" },
	{ mime = "application/rar",           run = "ouch" },
	{ mime = "application/xz",            run = "ouch" },
	{ mime = "application/xz",            run = "ouch" },
    { mime = "{image,audio,video}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo"},
	{ name = "*.md",	run = "glow" },
]
